ServiceInnovationLab/pancake-backend

public/api/docs/app.js
Auto corrected by following quotes
Click [here](https://awesomecode.io/projects/93/javascript_configs/4072) to configure it on awesomecode.io
=> Auto corrected by following quotes

spec/rails_helper.rb
Auto corrected by following RSpec/HookArgument
Click [here](https://awesomecode.io/projects/93/ruby_configs/20101) to configure it on awesomecode.io
=> Auto corrected by following RSpec/HookArgument

spec/api/v1/rebate_forms/create_spec.rb, spec/api/v1/signatures/create_spec.rb
Auto corrected by following RSpec/ExpectChange
Click [here](https://awesomecode.io/projects/93/ruby_configs/20233) to configure it on awesomecode.io
=> Auto corrected by following RSpec/ExpectChange

.travis.yml
has been broken since our repo name change
=> Fix continuous deployment

spec/controllers/rebate_forms_controller_spec.rb
We should test we give appropriate errors when validation fails. So I did.
run specs (travis did that for you)
=> Spec for when updating to bad values

Gemfile, Gemfile.lock, config/initializers/cors.rb
we need to talk to the api from github pages
=> Adding cors whitelist

spec/controllers/rebate_forms_controller_spec.rb
Auto corrected by following Layout/TrailingWhitespace
Click [here](https://awesomecode.io/projects/93/ruby_configs/20053) to configure it on awesomecode.io
=> Auto corrected by following Layout/TrailingWhitespace

app/controllers/docs_controller.rb, app/controllers/signatures_controller.rb, app/helpers/admin/signatures_helper.rb, app/models/signature.rb, app/serializers/serializable_signature.rb, app/views/admin/rebate_forms/show.html.haml, config/initializers/strong_resources.rb, config/routes.rb, db/migrate/20180426035741_add_name_to_signature.rb, db/schema.rb, db/seeds.rb, spec/api/v1/signatures/show_spec.rb, spec/controllers/signatures_controller_spec.rb, spec/factories/signatures.rb, spec/payloads/signature.rb
=> Names and roles on signatures

app/controllers/properties_controller.rb, db/seeds.rb
Auto corrected by following GeneralLayout
Click [here](https://awesomecode.io/projects/93/ruby_config_groups/667) to configure it on awesomecode.io
=> Auto corrected by following GeneralLayout

app/controllers/properties_controller.rb, config/routes.rb
Auto corrected by following PercentLiteral
Click [here](https://awesomecode.io/projects/93/ruby_config_groups/672) to configure it on awesomecode.io
=> Auto corrected by following PercentLiteral

spec/api/v1/properties/index_spec.rb, spec/api/v1/properties/show_spec.rb
Auto corrected by following RSpec/LeadingSubject
Click [here](https://awesomecode.io/projects/93/ruby_configs/20105) to configure it on awesomecode.io
=> Auto corrected by following RSpec/LeadingSubject

app/controllers/signatures_controller.rb, app/models/signature.rb
Something in how i refactored the code to please rubocop. Instead leaving it as obvious code and disabling rubocop.
=> Signatures weren't saving

spec/api/v1/properties/index_spec.rb, spec/api/v1/properties/show_spec.rb
Auto corrected by following EmptyLine
Click [here](https://awesomecode.io/projects/93/ruby_config_groups/668) to configure it on awesomecode.io
=> Auto corrected by following EmptyLine

spec/api/v1/properties/index_spec.rb, spec/api/v1/properties/show_spec.rb
Auto corrected by following RSpec/EmptyLineAfterSubject
Click [here](https://awesomecode.io/projects/93/ruby_configs/20099) to configure it on awesomecode.io
=> Auto corrected by following RSpec/EmptyLineAfterSubject

app/controllers/properties_controller.rb
only show the rates_payer and rate_bill data on #show
=> Extra info needs a valution_id

config/application.rb, config/environments/development.rb
So we can configure staging (and later prod) without a code change
=> Move cors settings into env

app/mailers/rebate_forms_mailer.rb, app/views/rebate_forms_mailer/applicant_mail.html.haml, app/views/rebate_forms_mailer/council_mail.html.haml
=> Convert html to haml

app/controllers/admin/rebate_forms_controller.rb, app/views/admin/rebate_forms/index.html.haml
Search by address for forms to sign
Closes #8
=> Search for application by address

config/routes.rb
our redirecting / to /app has broken the /admin path
this fixes it.
=> Fix the admin route

app/views/admin/rebate_forms/index.html.haml, app/views/admin/rebate_forms/show.html.haml
token got long - it looks messy
removing it.
=> Removing display of tokens

app/models/rates_bill.rb, app/serializers/serializable_rates_bill.rb
We need to add up the 2 values -- had to change what variable we return on the api
=> Show the total bill on the api

app/views/rebate_forms_mailer/applicant_mail.html.haml
=> Copy changes to the email

.gitignore, app/views/admin/rebate_forms/_fields.html.haml, app/views/admin/rebate_forms/_rates_bills.html.haml, app/views/admin/rebate_forms/index.html.haml, app/views/admin/rebate_forms/show.html.haml
=> Small ui tidy up

app/models/rates_bill.rb
funky decimal points are in our API
this formats them instead
=> Clean up decimals on number formatting

spec/requests/root_requests_spec.rb
Spec to ensure the redirect to /app/ keeps working
=> Added spec for redirecting to app

app/views/rebate_forms_mailer/applicant_mail.html.haml
closes https://github.com/ServiceInnovationLab/pancake-frontend/issues/258
=> Updated email copy

app/assets/stylesheets/admin/rebate_form.css, app/assets/stylesheets/application.css, app/views/admin/rebate_forms/_fields.html.haml, app/views/admin/rebate_forms/_property.haml, app/views/admin/rebate_forms/_signatures.html.haml, app/views/admin/rebate_forms/index.html.haml, app/views/admin/rebate_forms/show.html.haml, app/views/layouts/application.html.haml
=> Layout changes to keep signature size in check

app/controllers/rebate_forms_controller.rb, app/models/rebate_form.rb, spec/controllers/rebate_forms_controller_spec.rb, spec/factories/properties.rb
The rebate isn't calculating on staging and i don't know why.
This will both add a test, and also raise exceptions if something isn't right on the server.
=> Tests that rebate is calculated by the controller

app/assets/stylesheets/admin/rebate_form.css
Auto corrected by following number-no-trailing-zeros
Click [here](https://awesomecode.io/projects/93/css_configs/245) to configure it on awesomecode.io
=> Auto corrected by following number-no-trailing-zeros

app/views/rebate_forms_mailer/applicant_mail.html.haml
Council requested that we changed date to reflect that close off date of 2nd July
Changed content in email to applicant to reflect council request (30 June changed to 2 July)
=> Changed content about close off date

app/assets/javascripts/direct-uploads.js
Auto corrected by following padded-blocks
Click [here](https://awesomecode.io/projects/93/javascript_configs/4110) to configure it on awesomecode.io
=> Auto corrected by following padded-blocks

app/assets/javascripts/direct-uploads.js
Auto corrected by following arrow-parens
Click [here](https://awesomecode.io/projects/93/javascript_configs/4034) to configure it on awesomecode.io
=> Auto corrected by following arrow-parens

app/assets/javascripts/direct-uploads.js
Auto corrected by following object-curly-spacing
Click [here](https://awesomecode.io/projects/93/javascript_configs/4107) to configure it on awesomecode.io
=> Auto corrected by following object-curly-spacing

spec/controllers/properties_controller_spec.rb, spec/controllers/rebate_forms_controller_spec.rb, spec/controllers/signatures_controller_spec.rb, spec/models/rebate_form_spec.rb, spec/requests/root_requests_spec.rb
Auto corrected by following RSpec/EmptyLineAfterHook
Click [here](https://awesomecode.io/projects/93/ruby_configs/29156) to configure it on awesomecode.io
=> Auto corrected by following RSpec/EmptyLineAfterHook

Gemfile.lock
=> Sprockets upgrade

spec/views/admin/councils/edit.html.haml_spec.rb, spec/views/admin/councils/index.html.haml_spec.rb, spec/views/admin/councils/new.html.haml_spec.rb, spec/views/admin/councils/show.html.haml_spec.rb
Auto corrected by following Ruby RSpec/HookArgument
Click [here](https://awesomecode.io/projects/93/ruby_configs/25689) to configure it on awesomecode.io
=> Auto corrected by following Ruby RSpec/HookArgument

.travis.yml
=> Add install and asset compile to deploy

app/models/rebate_form.rb
=> Associate with the property record of the same year

db/seeds/rates_2019.csv
=> try one row

app/views/admin/rebate_forms/index.html.haml, app/views/admin/rebate_forms/show.html.haml
=> Show the year the application is for

app/services/rates_importer_service.rb, lib/tasks/rates.rake
=> Clear old data before running import

app/controllers/admin/rebate_forms_controller.rb, app/policies/rebate_form_policy.rb, spec/controllers/admin/rebate_forms_controller_spec.rb, spec/factories/properties.rb, spec/policies/rebate_form_policy_spec.rb
fixes https://github.com/ServiceInnovationLab/pancake-frontend/issues/492
=> Fix attachments

app/views/admin/rebate_forms/_form.html.haml
Allows input of fraction numbers on income field
=> Fixes allowed inputs on income edit field

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/views/layouts/_menu.haml, app/views/welcome/index.html.haml
Example from my dev database (not real data)
=> LOTS OF GRAPHS

app/views/welcome/index.html.haml
=> Adding witnessed hour of the day

app/views/welcome/index.html.haml
=> Release "witnessing by hour of day" to production

app/views/admin/rebate_forms/_artefact.haml
=> use yes instead of true

spec/controllers/admin/rebate_forms_controller_spec.rb, spec/helpers/rebate_forms_helper_spec.rb
=> Deploy to production

app/helpers/rebate_forms_helper.rb, spec/helpers/rebate_forms_helper_spec.rb
closes https://github.com/ServiceInnovationLab/pancake-frontend/issues/601
=> Fix grammar on pdf artefact when no dependents

app/javascript/components/CustomerApplications.js
Added alt text for blue right arrow.
=> Added alt text for blue right arrow.

app/assets/stylesheets/admin/rebate_form.css, app/javascript/components/IncomeDeclaration.js, app/views/admin/rebate_forms/_signature_done_header.html.haml, app/views/admin/rebate_forms/generateqr.html.haml
=> Added back button on QR page.

app/javascript/components/IncomeDeclaration.js
=> add partner or joint homeowner backin

app/views/admin/rebate_forms/index.html.haml, spec/features/admin/rebate_forms/edit_spec.rb
Changed wording - applications to search.
=> Changed wording - applications to search.

app/javascript/containers/CustomersSummary.js
=> reset state on remove of processed

Gemfile, Gemfile.lock
Fixes broken build in dev branch
=> Shaving travis the yak

app/assets/stylesheets/application.css
=> add read only styles

config/environments/production.rb, config/environments/staging.rb
=> include  active_storate service amazon

lib/tasks/rates.rake
=> remove importer.clear call

app/serializers/serializable_council.rb, bin/docker_web_aws
=> add has address lookups attribute to API and load tauranga data

spec/factories/councils.rb, spec/payloads/council.rb
=> update test data

app/services/rates_importer_service.rb
=> override with latest rates data for property

bin/docker_web_aws
=> rake in some tauranga data

app/views/admin/rebate_forms/_edit_header.html.haml, app/views/admin/rebate_forms/edit.html.haml, app/views/admin/rebate_forms_council_details/edit.html.haml, spec/features/admin/rebate_forms/edit_spec.rb
Karen asked for some changes to the headers on the edit forms.
=> Bugfix rr 506 update headers

app/services/rates_importer_service.rb, bin/docker_web_aws
=> run rake tasks kapiti and tauranga on UAT with latest data

db/migrate/20190620204258_add_total_rates_location_to_rebate_form.rb
=> add gaurd to total rates in migration

lib/tasks/rates.rake
=> remove extra data from kapiti rake task

app/services/rates_importer_service.rb
=> remove quotes from kapiti blah

app/services/rates_importer_service.rb, app/services/rebate_forms_service.rb
=> update for prod

app/javascript/components/inputs.js, app/javascript/containers/RebateForm.js, spec/features/admin/rebate_forms/edit_spec.rb
Only render moved within rating year question if lived in property july 1 is false
=> add condtional render of 'Moved within rating year' based on 'Lived in property 1 July 2018'

bin/docker_web_aws
=> Comment rake rates tasks from aws script as they are completed for now

app/javascript/components/inputs.js, app/javascript/containers/RebateForm.js, app/javascript/helpers/data.js, spec/factories/rebate_forms.rb, spec/features/admin/rebate_forms/edit_spec.rb, spec/features/admin/rebate_forms/show_spec.rb
=> add income less than 5k field

app/services/rates_importer_service.rb, bin/docker_web_aws
=> fix rates importer and uncomment docker script

app/assets/stylesheets/application.css, app/javascript/components/inputs.js
=> text area read only

app/javascript/containers/RebateForm.js
=> only render on read only if content

config/initializers/dotenv.rb
=> comment out dotenv declaration

app/assets/stylesheets/admin/rebate_form.css, app/views/admin/rebate_forms/_decline_actions.html.haml, app/views/admin/rebate_forms/_navigation.html.haml, app/views/admin/rebate_forms/_process_actions.html.haml
Adds text below the navigation button icons
=> Add text to navigation buttons

app/assets/stylesheets/admin/rebate_form.css, app/controllers/admin/declined_rebate_forms_controller.rb, app/javascript/components/SummaryRow.js, app/javascript/components/SummaryTable.js, app/javascript/containers/CustomersSummary.js, app/views/admin/rebate_forms/_signature_done_header.html.haml, spec/factories/users.rb, spec/features/admin/declined_rebate_forms/declined_rebate_forms_controller_spec.rb
=> add declined by column

app/controllers/rebate_forms_controller.rb, app/controllers/signatures_controller.rb
=> already been
